import { useColors } from '@portfolio/ui';
import { Ionicons } from '@expo/vector-icons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

export default function CalendarTabScreen() {
  const colors = useColors();
  const router = useRouter();
  const [selected, setSelected] = useState(18);
  const [monthOffset, setMonthOffset] = useState(0);
  const monthDate = new Date(2025, 5 + monthOffset, 1);
  const monthLabel = new Intl.DateTimeFormat('es-ES', { month: 'long', year: 'numeric' }).format(monthDate);
  const days = Array.from({ length: 7 }, (_, index) => {
    const date = 16 + index;
    const weekday = new Intl.DateTimeFormat('es-ES', { weekday: 'short' }).format(new Date(monthDate.getFullYear(), monthDate.getMonth(), date)).replace('.', '');
    return { day: monthOffset === 0 && date === 18 ? 'Hoy' : weekday.charAt(0).toUpperCase() + weekday.slice(1), date };
  });
  const Task = ({ icon, color, title, meta, action, route }: { icon: keyof typeof Ionicons.glyphMap; color: string; title: string; meta: string; action?: string; route: string }) => <Pressable accessibilityRole="button" onPress={() => action === 'soil' ? router.push('/modal/check-soil-sheet' as any) : router.push(route as any)} style={[styles.task, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.taskIcon, { backgroundColor: color + '20' }]}><Ionicons name={icon} size={20} color={color} /></View><View style={{ flex: 1 }}><Text style={[styles.taskTitle, { color: colors.text }]}>{title}</Text><Text style={[styles.taskMeta, { color: colors.textSecondary }]}>{meta}</Text></View><Ionicons name="chevron-forward" size={18} color={colors.textSecondary} /></Pressable>;

  return (
    <SafeAreaView style={[styles.container, { backgroundColor: colors.background }]} edges={['top']}>
      <View style={[styles.header, { borderBottomColor: colors.border }]}><View><Text style={[styles.kicker, { color: colors.primary }]}>SEMILLA · ORGANIZA TUS CUIDADOS</Text><Text style={[styles.title, { color: colors.text }]}>Calendario</Text></View><Pressable accessibilityRole="button" onPress={() => router.push('/reminder/new' as any)} style={[styles.addButton, { backgroundColor: colors.primaryDark }]}><Ionicons name="add" size={18} color="#fff" /><Text style={styles.addText}>Nuevo</Text></Pressable></View>
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.content}>
        <View style={styles.monthRow}><Pressable accessibilityRole="button" accessibilityLabel="Mes anterior" onPress={() => setMonthOffset((value) => value - 1)} style={styles.monthButton}><Ionicons name="chevron-back" size={20} color={colors.textSecondary} /></Pressable><View><Text style={[styles.month, { color: colors.text }]}>{monthLabel.charAt(0).toUpperCase() + monthLabel.slice(1)}</Text><Text style={[styles.monthSub, { color: colors.textSecondary }]}>Primavera · Madrid</Text></View><Pressable accessibilityRole="button" accessibilityLabel="Mes siguiente" onPress={() => setMonthOffset((value) => value + 1)} style={styles.monthButton}><Ionicons name="chevron-forward" size={20} color={colors.textSecondary} /></Pressable></View>
        <View style={[styles.week, { backgroundColor: colors.surface, borderColor: colors.border }]}>{days.map((item) => <Pressable key={item.date} onPress={() => setSelected(item.date)} style={[styles.day, selected === item.date && { backgroundColor: colors.primary }]}><Text style={[styles.dayName, { color: selected === item.date ? '#fff' : colors.textSecondary }]}>{item.day}</Text><Text style={[styles.dayNumber, { color: selected === item.date ? '#fff' : colors.text }]}>{item.date}</Text>{[16, 18, 20].includes(item.date) && <View style={[styles.dayDot, { backgroundColor: selected === item.date ? '#fff' : colors.warning }]} />}</Pressable>)}</View>
        <View style={[styles.tip, { backgroundColor: colors.surfaceAlt, borderColor: colors.border }]}><Ionicons name="sunny-outline" size={21} color={colors.warning} /><View style={{ flex: 1 }}><Text style={[styles.tipTitle, { color: colors.text }]}>Consejo de Semillita</Text><Text style={[styles.tipText, { color: colors.textSecondary }]}>Agrupa los cuidados al amanecer: el sustrato conserva mejor la humedad y evitas mojar hojas con sol directo.</Text></View></View>
        <View style={styles.sectionRow}><Text style={[styles.section, { color: colors.text }]}>Hoy, miércoles 18</Text><Text style={[styles.count, { color: colors.primary }]}>3 cuidados</Text></View>
        <Task icon="finger-print-outline" color={colors.warning} title="Comprobar sustrato · Albahaca Limón" meta="09:00 · Diagnóstico de 2 cm antes de regar" action="soil" route="/plant/albahaca" />
        <Task icon="refresh-outline" color={colors.info} title="Girar maceta · Menta Piperita" meta="11:00 · Para un follaje simétrico" route="/plant/menta" />
        <Task icon="nutrition-outline" color={colors.primary} title="Revisar floración · Tomate Cherry" meta="18:30 · Abono suave de guano orgánico" route="/plant/tomate-cherry" />
        <View style={styles.sectionRow}><Text style={[styles.section, { color: colors.text }]}>Próximos días</Text><Text style={[styles.count, { color: colors.textSecondary }]}>Ver todo</Text></View>
        <View style={[styles.upcoming, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.upcomingDate, { color: colors.primary }]}>JUEVES 19</Text><Text style={[styles.upcomingText, { color: colors.text }]}>Mapear sombras de la terraza</Text><Text style={[styles.upcomingMeta, { color: colors.textSecondary }]}>Semillita recomienda medir a las 11:00 y 16:00</Text><View style={[styles.divider, { backgroundColor: colors.border }]} /><Text style={[styles.upcomingDate, { color: colors.primary }]}>VIERNES 20</Text><Text style={[styles.upcomingText, { color: colors.text }]}>Revisión preventiva de plagas</Text><Text style={[styles.upcomingMeta, { color: colors.textSecondary }]}>Oídio, pulgón y araña roja</Text></View>
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1 }, header: { minHeight: 76, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomWidth: 1 }, kicker: { fontSize: 10, fontWeight: '900', letterSpacing: 1 }, title: { fontSize: 25, fontWeight: '900', marginTop: 2 }, addButton: { minHeight: 42, paddingHorizontal: 15, borderRadius: 14, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 5 }, addText: { color: '#fff', fontSize: 13, fontWeight: '800' }, content: { padding: 16, gap: 13, paddingBottom: 100 }, monthRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, month: { textAlign: 'center', fontSize: 19, fontWeight: '900' }, monthSub: { textAlign: 'center', fontSize: 12, marginTop: 2 }, monthButton: { width: 44, height: 44, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, week: { borderRadius: 18, borderWidth: 1, paddingVertical: 10, paddingHorizontal: 5, flexDirection: 'row', justifyContent: 'space-around' }, day: { width: 40, minHeight: 55, borderRadius: 13, alignItems: 'center', justifyContent: 'center', gap: 3 }, dayName: { fontSize: 10, fontWeight: '700' }, dayNumber: { fontSize: 16, fontWeight: '900' }, dayDot: { width: 5, height: 5, borderRadius: 3 }, tip: { borderRadius: 17, borderWidth: 1, padding: 13, flexDirection: 'row', gap: 10 }, tipTitle: { fontSize: 14, fontWeight: '800' }, tipText: { fontSize: 12, lineHeight: 17, marginTop: 3 }, sectionRow: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', marginTop: 3 }, section: { fontSize: 18, fontWeight: '900' }, count: { fontSize: 12, fontWeight: '800' }, task: { minHeight: 73, borderRadius: 17, borderWidth: 1, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 10 }, taskIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, taskTitle: { fontSize: 14, fontWeight: '800' }, taskMeta: { fontSize: 11, lineHeight: 16, marginTop: 3 }, upcoming: { borderRadius: 18, borderWidth: 1, padding: 14 }, upcomingDate: { fontSize: 10, fontWeight: '900', letterSpacing: 1, marginTop: 2 }, upcomingText: { fontSize: 14, fontWeight: '800', marginTop: 4 }, upcomingMeta: { fontSize: 12, lineHeight: 17, marginTop: 2 }, divider: { height: 1, marginVertical: 12 },
});
