-- Keep the database catalog IDs in parity with the native client catalog.
-- Existing rows are aligned; missing rows are added for FK-safe plant sync.
insert into crops (id, name, emoji, category, days_to_harvest_min, days_to_harvest_max, sun_needs, water_needs, spacing_cm) values
  ('tomate', 'Tomate', '🍅', 'frutas', 60, 85, 'full', 'high', 60),
  ('pimiento', 'Pimiento', '🫑', 'frutas', 70, 90, 'full', 'medium', 50),
  ('berenjena', 'Berenjena', '🍆', 'frutas', 65, 80, 'full', 'medium', 60),
  ('fresa', 'Fresa', '🍓', 'frutas', 90, 120, 'full', 'medium', 30),
  ('lechuga', 'Lechuga', '🥬', 'hojas', 45, 70, 'partial', 'medium', 25),
  ('espinaca', 'Espinaca', '🌿', 'hojas', 40, 60, 'partial', 'medium', 15),
  ('acelga', 'Acelga', '🥦', 'hojas', 50, 70, 'partial', 'medium', 30),
  ('rucula', 'Rúcula', '🌱', 'hojas', 30, 45, 'partial', 'low', 15),
  ('canonigos', 'Canónigos', '🌿', 'hojas', 50, 70, 'partial', 'low', 10),
  ('zanahoria', 'Zanahoria', '🥕', 'raices', 70, 90, 'full', 'medium', 8),
  ('rabano', 'Rábano', '🥕', 'raices', 25, 35, 'partial', 'medium', 5),
  ('remolacha', 'Remolacha', '🟣', 'raices', 55, 75, 'full', 'medium', 10),
  ('patata', 'Patata', '🥔', 'raices', 70, 120, 'full', 'medium', 35),
  ('nabo', 'Nabo', '🫛', 'raices', 45, 65, 'full', 'medium', 15),
  ('judia-verde', 'Judía verde', '🫘', 'legumbres', 50, 70, 'full', 'medium', 20),
  ('guisante', 'Guisante', '🟢', 'legumbres', 60, 80, 'full', 'medium', 10),
  ('haba', 'Haba', '🫘', 'legumbres', 90, 120, 'full', 'medium', 25),
  ('brocoli', 'Brócoli', '🥦', 'cruciferas', 65, 90, 'full', 'medium', 50),
  ('coliflor', 'Coliflor', '🌸', 'cruciferas', 70, 100, 'full', 'medium', 55),
  ('col', 'Col / Repollo', '🥬', 'cruciferas', 80, 120, 'full', 'medium', 50),
  ('kale', 'Kale (Col rizada)', '🌿', 'cruciferas', 55, 75, 'full', 'medium', 45),
  ('calabacin', 'Calabacín', '🥒', 'cucurbitaceas', 45, 60, 'full', 'high', 80),
  ('pepino', 'Pepino', '🥒', 'cucurbitaceas', 50, 65, 'full', 'high', 50),
  ('calabaza', 'Calabaza', '🎃', 'cucurbitaceas', 90, 120, 'full', 'medium', 100),
  ('melon', 'Melón', '🍈', 'cucurbitaceas', 75, 100, 'full', 'medium', 80),
  ('sandia', 'Sandía', '🍉', 'cucurbitaceas', 80, 110, 'full', 'high', 100),
  ('albahaca', 'Albahaca', '🌿', 'aromaticas', 30, 50, 'full', 'medium', 25),
  ('perejil', 'Perejil', '🌱', 'aromaticas', 70, 90, 'partial', 'medium', 20),
  ('cilantro', 'Cilantro', '🌿', 'aromaticas', 30, 45, 'partial', 'medium', 15),
  ('romero', 'Romero', '🌿', 'aromaticas', 90, 180, 'full', 'low', 50),
  ('tomillo', 'Tomillo', '🌿', 'aromaticas', 70, 120, 'full', 'low', 30),
  ('menta', 'Menta', '🌿', 'aromaticas', 30, 60, 'partial', 'medium', 30),
  ('ajo', 'Ajo', '🧄', 'bulbos', 180, 240, 'full', 'low', 12),
  ('cebolla', 'Cebolla', '🧅', 'bulbos', 90, 150, 'full', 'low', 15),
  ('puerro', 'Puerro', '🌿', 'bulbos', 120, 180, 'full', 'medium', 15),
  ('guindilla', 'Guindilla / Chile', '🌶️', 'frutas', 75, 100, 'full', 'medium', 40),
  ('apio', 'Apio', '🥬', 'hojas', 100, 140, 'partial', 'high', 25),
  ('esparrago', 'Espárrago', '🌿', 'hojas', 730, 1095, 'full', 'low', 40),
  ('salvia', 'Salvia', '🌿', 'aromaticas', 75, 100, 'full', 'low', 45),
  ('oregano', 'Orégano', '🌿', 'aromaticas', 60, 90, 'full', 'low', 30),
  ('eneldo', 'Eneldo', '🌿', 'aromaticas', 40, 70, 'full', 'medium', 20),
  ('hinojo', 'Hinojo', '🌿', 'aromaticas', 65, 90, 'full', 'low', 45),
  ('maiz', 'Maíz', '🌽', 'frutas', 70, 100, 'full', 'high', 30),
  ('frambuesa', 'Frambuesa', '🍓', 'frutas', 365, 730, 'partial', 'medium', 45),
  ('arandano', 'Arándano', '🫐', 'frutas', 730, 1460, 'full', 'medium', 100),
  ('coles-bruselas', 'Coles de Bruselas', '🥦', 'cruciferas', 90, 120, 'full', 'medium', 50),
  ('pak-choi', 'Pak choi', '🥬', 'cruciferas', 45, 70, 'partial', 'medium', 25),
  ('escarola', 'Escarola', '🥬', 'hojas', 85, 100, 'partial', 'medium', 30),
  ('berros', 'Berros', '🌿', 'hojas', 30, 50, 'partial', 'high', 15),
  ('boniato', 'Boniato / Batata', '🍠', 'raices', 90, 120, 'full', 'medium', 40),
  ('chirivi', 'Chirivía', '🥕', 'raices', 100, 120, 'full', 'medium', 10),
  ('lenteja', 'Lenteja', '🫘', 'legumbres', 80, 110, 'full', 'low', 8),
  ('garbanzo', 'Garbanzo', '🫛', 'legumbres', 90, 120, 'full', 'low', 15),
  ('edamame', 'Edamame', '🫘', 'legumbres', 70, 90, 'full', 'medium', 15),
  ('chalota', 'Chalota', '🧅', 'bulbos', 90, 120, 'full', 'low', 15),
  ('cebollino', 'Cebollino', '🌿', 'aromaticas', 30, 60, 'partial', 'medium', 20),
  ('estragon', 'Estragón', '🌿', 'aromaticas', 60, 90, 'full', 'low', 40),
  ('mejorana', 'Mejorana', '🌿', 'aromaticas', 60, 90, 'full', 'low', 25),
  ('stevia', 'Stevia', '🍃', 'medicinales', 90, 120, 'full', 'medium', 40),
  ('ruibarbo', 'Ruibarbo', '🌿', 'medicinales', 365, 730, 'partial', 'medium', 80),
  ('verbena', 'Verbena de limón', '🌿', 'medicinales', 90, 150, 'full', 'low', 50),
  ('borraja', 'Borraja', '💙', 'medicinales', 50, 70, 'full', 'low', 30),
  ('manzanilla', 'Manzanilla', '🌼', 'medicinales', 50, 70, 'full', 'low', 20),
  ('lavanda', 'Lavanda', '💜', 'medicinales', 90, 180, 'full', 'low', 50),
  ('alcachofa', 'Alcachofa', '🌸', 'frutas', 120, 150, 'full', 'medium', 90),
  ('pimiento-padron', 'Pimiento de Padrón', '🫑', 'frutas', 65, 80, 'full', 'medium', 45),
  ('tomate-cherry', 'Tomate cherry', '🍅', 'frutas', 55, 75, 'full', 'high', 50),
  ('tomatillo', 'Tomatillo', '🫑', 'frutas', 70, 90, 'full', 'medium', 60),
  ('okra', 'Okra / Quimbombó', '🌿', 'frutas', 55, 65, 'full', 'medium', 50),
  ('girasol', 'Girasol', '🌻', 'frutas', 70, 90, 'full', 'medium', 60),
  ('mora', 'Mora', '🫐', 'frutas', 365, 730, 'full', 'medium', 100),
  ('grosella', 'Grosella', '❤️', 'frutas', 365, 730, 'full', 'medium', 100),
  ('higo', 'Higo / Higuera', '🫐', 'frutas', 730, 1460, 'full', 'low', 300),
  ('pepinillo', 'Pepinillo encurtido', '🥒', 'cucurbitaceas', 45, 55, 'full', 'high', 40),
  ('mizuna', 'Mizuna', '🌿', 'hojas', 30, 45, 'partial', 'medium', 20),
  ('radicchio', 'Radicchio / Achicoria roja', '🥬', 'hojas', 80, 100, 'full', 'low', 30),
  ('endivias', 'Endivia', '🥬', 'hojas', 90, 120, 'shade', 'medium', 20),
  ('acedera', 'Acedera', '🌿', 'hojas', 50, 60, 'partial', 'medium', 30),
  ('amaranto', 'Amaranto', '🌿', 'hojas', 60, 90, 'full', 'low', 40),
  ('espinaca-nz', 'Espinaca de N. Zelanda', '🌿', 'hojas', 55, 70, 'full', 'low', 40),
  ('batavia', 'Lechuga Batavia', '🥬', 'hojas', 60, 75, 'partial', 'medium', 30),
  ('remolacha-hoja', 'Acelga roja / Remolacha de hoja', '🌿', 'hojas', 50, 70, 'partial', 'medium', 25),
  ('esparrago-triguero', 'Espárrago triguero', '🌿', 'hojas', 730, 1095, 'full', 'low', 40),
  ('lechuga-romana', 'Lechuga romana / Cos', '🥬', 'hojas', 70, 80, 'partial', 'medium', 30),
  ('daikon', 'Daikon / Rábano blanco', '🥕', 'raices', 50, 70, 'full', 'medium', 20),
  ('apionabo', 'Apionabo / Apio-nabo', '🥕', 'raices', 120, 150, 'partial', 'high', 30),
  ('salsifi', 'Salsifí', '🥕', 'raices', 120, 150, 'full', 'low', 15),
  ('chufa', 'Chufa', '🌿', 'raices', 150, 180, 'full', 'medium', 15),
  ('topinambur', 'Topinambur / Alcachofa de Jerusalén', '🥕', 'raices', 150, 180, 'full', 'low', 30),
  ('jengibre', 'Jengibre', '🌿', 'aromaticas', 210, 240, 'partial', 'medium', 20),
  ('curcuma', 'Cúrcuma', '🌿', 'aromaticas', 240, 300, 'partial', 'medium', 25),
  ('tirabeques', 'Tirabeques / Guisantes mangetout', '🟢', 'legumbres', 55, 75, 'full', 'medium', 10),
  ('alubia', 'Alubia / Judía pinta', '🫘', 'legumbres', 75, 100, 'full', 'medium', 20),
  ('cacahuete', 'Cacahuete', '🥜', 'legumbres', 120, 150, 'full', 'low', 30),
  ('veza', 'Veza / Arveja', '🌿', 'legumbres', 150, 180, 'full', 'low', 10),
  ('garrofon', 'Garrofón / Judión', '🫘', 'legumbres', 80, 110, 'full', 'medium', 30),
  ('lombarda', 'Lombarda / Col morada', '🥬', 'cruciferas', 80, 100, 'full', 'medium', 50),
  ('col-china', 'Col china / Napa', '🥬', 'cruciferas', 50, 70, 'partial', 'medium', 40),
  ('romanesco', 'Romanesco', '🟢', 'cruciferas', 75, 100, 'full', 'medium', 55),
  ('col-savoya', 'Col de Saboya', '🥬', 'cruciferas', 80, 120, 'full', 'medium', 50),
  ('nabicol', 'Nabicol / Colinabo sueco', '🥕', 'cruciferas', 90, 120, 'full', 'medium', 30),
  ('brocoli-morado', 'Brócoli morado / Brócoli de Sicilia', '🟣', 'cruciferas', 85, 110, 'full', 'medium', 50),
  ('colinabo', 'Colinabo', '🥬', 'cruciferas', 50, 70, 'full', 'medium', 25),
  ('calabaza-butternut', 'Calabaza Butternut', '🎃', 'cucurbitaceas', 100, 120, 'full', 'medium', 80),
  ('chayote', 'Chayote / Chayota', '🥒', 'cucurbitaceas', 120, 150, 'full', 'medium', 100),
  ('calabacin-amarillo', 'Calabacín amarillo', '🌻', 'cucurbitaceas', 45, 60, 'full', 'high', 80),
  ('hierbabuena', 'Hierbabuena', '🌿', 'aromaticas', 60, 90, 'partial', 'medium', 30),
  ('perifollo', 'Perifollo', '🌿', 'aromaticas', 40, 60, 'shade', 'medium', 15),
  ('laurel', 'Laurel', '🌿', 'aromaticas', 365, 730, 'full', 'low', 200),
  ('comino', 'Comino', '🌿', 'aromaticas', 120, 150, 'full', 'low', 20),
  ('anis', 'Anís verde', '🌿', 'aromaticas', 120, 150, 'full', 'medium', 30),
  ('albahaca-morada', 'Albahaca morada', '🌿', 'aromaticas', 30, 50, 'full', 'medium', 25),
  ('albahaca-tailandesa', 'Albahaca tailandesa', '🌿', 'aromaticas', 35, 55, 'full', 'medium', 25),
  ('ajedrea', 'Ajedrea', '🌿', 'aromaticas', 60, 90, 'full', 'low', 30),
  ('hisopo', 'Hisopo', '🌿', 'medicinales', 70, 100, 'full', 'low', 40),
  ('alcaravea', 'Alcaravea / Caraway', '🌿', 'aromaticas', 365, 400, 'full', 'low', 30),
  ('tomillo-limonero', 'Tomillo limonero', '🌿', 'aromaticas', 70, 120, 'full', 'low', 25),
  ('coriandro', 'Cilantro (semillas)', '🌿', 'aromaticas', 90, 120, 'full', 'low', 20),
  ('melisa', 'Melisa / Toronjil', '🌿', 'medicinales', 60, 90, 'partial', 'medium', 35),
  ('toronjil', 'Toronjil / Melisa', '🌿', 'medicinales', 60, 90, 'partial', 'medium', 40),
  ('nepeta', 'Nepeta / Hierba gatera', '🌿', 'medicinales', 70, 100, 'full', 'low', 40),
  ('ruda', 'Ruda', '🌿', 'medicinales', 75, 100, 'full', 'low', 50),
  ('bergamota', 'Bergamota (Monarda)', '🌸', 'medicinales', 90, 120, 'partial', 'medium', 50),
  ('malva', 'Malva', '🌸', 'medicinales', 70, 90, 'full', 'low', 60),
  ('cebolleta', 'Cebolleta / Cebolla de verdeo', '🧅', 'bulbos', 60, 80, 'full', 'medium', 5),
  ('ajo-tierno', 'Ajo tierno / Ajete', '🧄', 'bulbos', 90, 120, 'full', 'low', 12),
  ('cebolla-morada', 'Cebolla morada', '🧅', 'bulbos', 90, 150, 'full', 'low', 15),
  ('ajo-elefante', 'Ajo elefante', '🧄', 'bulbos', 200, 240, 'full', 'low', 20),
  ('cebolla-francesa', 'Cebolla francesa', '🧅', 'bulbos', 150, 200, 'full', 'low', 10),
  ('ajo-negro', 'Ajo negro', '🧄', 'bulbos', 180, 240, 'full', 'low', 12),
  ('cipolla-borettana', 'Cebolla Borettana / Cebollita', '🧅', 'bulbos', 100, 130, 'full', 'low', 8),
  ('capuchina', 'Capuchina / Mastuerzo', '🌸', 'medicinales', 45, 60, 'full', 'low', 30),
  ('calendula', 'Caléndula', '🌼', 'medicinales', 50, 70, 'full', 'low', 30),
  ('tagetes', 'Tagetes / Clavel moro', '🌼', 'medicinales', 50, 60, 'full', 'low', 20),
  ('equinacea', 'Equinácea', '🌸', 'medicinales', 365, 730, 'full', 'low', 50),
  ('hiperico', 'Hipérico / Hierba de San Juan', '🌼', 'medicinales', 365, 730, 'full', 'low', 60),
  ('valeriana', 'Valeriana', '🌸', 'medicinales', 365, 730, 'partial', 'medium', 100),
  ('aloe', 'Aloe vera', '🌿', 'medicinales', 180, 365, 'full', 'low', 40),
  ('violeta', 'Violeta / Pensamiento', '💜', 'medicinales', 120, 150, 'partial', 'medium', 20),
  ('rosa-mosqueta', 'Rosa mosqueta', '🌹', 'medicinales', 365, 730, 'full', 'low', 150),
  ('azafran', 'Azafrán', '🌸', 'medicinales', 90, 120, 'full', 'low', 10),
  ('fresa-silvestre', 'Fresilla / Fresa silvestre', '🍓', 'frutas', 90, 120, 'partial', 'medium', 20),
  ('grosellaespinosa', 'Grosella espinosa / Uva crispa', '🍏', 'frutas', 365, 730, 'full', 'medium', 100),
  ('melocoton', 'Melocotón / Nectarina', '🍑', 'frutas', 1095, 1460, 'full', 'medium', 250),
  ('limon', 'Limonero', '🍋', 'frutas', 365, 730, 'full', 'medium', 200),
  ('naranja', 'Naranjo / Mandarino', '🍊', 'frutas', 365, 730, 'full', 'medium', 250),
  ('vid', 'Vid / Parra', '🍇', 'frutas', 1095, 1460, 'full', 'low', 300),
  ('manzano', 'Manzano / Peral', '🍎', 'frutas', 1095, 1460, 'full', 'low', 300),
  ('cerezas', 'Cerezo', '🍒', 'frutas', 1095, 1460, 'full', 'low', 400)
on conflict (id) do update set
  name = excluded.name,
  emoji = excluded.emoji,
  category = excluded.category,
  days_to_harvest_min = excluded.days_to_harvest_min,
  days_to_harvest_max = excluded.days_to_harvest_max,
  sun_needs = excluded.sun_needs,
  water_needs = excluded.water_needs,
  spacing_cm = excluded.spacing_cm;
